### ISSUE TITLE
Encode raw data fast

### ISSUE THREAD

**Issue by yoki123** [crazyhatfish/ProtoPy#4]
If I already have my messages represented as `list` and `dict`, I must construct intermediate objects which waste a lot of overhead. I would like to encode by a way like

```
buf = encode_dict(CustomMessageType, dict_data)
```

or

```
buf = CustomMessageType.encode_dict(dict_data)
```

Moving `__lookup__` from  object variable to class variable will decrease overhead and be helpful to complete this feature.

please forgive my poor English :)

**Comment by crazyhatfish** [comment]
Another good idea, although I'm hesitant to make `__lookup__` a class variable. The idea originally was to give each instance of `Message` its own instance of `__lookup__` so that monkey patching would be easier. If you can think of another use case where having `__lookup__` be class variable would be of benefit, I'd be happy to reconsider.

Your English is great, so don't worry about it, much better than my second language.
